export const GET_USER = 'GET_USER'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILED = 'GET_USER_FAILED'

export const GET_USER_STARRED_REPO = 'GET_USER_STARRED_REPO'
export const GET_USER_STARRED_REPO_SUCCESS = 'GET_USER_STARRED_REPO_SUCCESS'
export const GET_USER_STARRED_REPO_FAILED = 'GET_USER_STARRED_REPO_FAILED'

export const GET_REPO = 'GET_REPO'
export const GET_REPO_SUCCESS = 'GET_REPO_SUCCESS'
export const GET_REPO_FAILED = 'GET_REPO_FAILED'

export const GET_REPO_STARGAZERS = 'GET_REPO_STARGAZERS'
export const GET_REPO_STARGAZERS_SUCCESS = 'GET_REPO_STARGAZERS_SUCCESS'
export const GET_REPO_STARGAZERS_FAILED = 'GET_REPO_STARGAZERS_FAILED'
